### ISSUE TITLE
Provide a semester separation value in sequence_matrix

### ISSUE THREAD

**Issue by pushkarkadam** [wsu-tss/student_pathway_project#16]
Currently, the semesters are separated by hard coding the variable `august = 8` in the module `adjacency_method.sequence_matrix`.

This was done assuming all the results for the autumn semester will be released by at least the month of August.

Provide the user with the option to set the variable as needed while maintaining a default value.

**TODO**

- [x] Add default `sem_separator_month=8` in the function declaration
- [x] Change `august` variable in the code to `sem_separator_month`
- [x] Write test functions to check the default value

**Recommendation**:

`M, _, _ = sequence_matrix(data, sem_separator_month=8)`
