### ISSUE TITLE
Engineering data with cohort units

### ISSUE THREAD

**Issue by pushkarkadam** [wsu-tss/student_pathway_project#40]
There are several units in the data set. These are not particular to the cohort.

**TODO**:

- [x] Create a csv file with the list of `unit_number` and `unit_name`.
- [x] Create a python module for importing the units data.
- [x] Convert the unit data into a list.
- [x] Remove the row values that are not a part of unit list.
